name: Build Redis Server 7.2.11 on RHEL 7.9

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Build Redis in RHEL 7.9 Container
      run: |
        # 创建临时构建脚本
        cat > build-redis.sh << 'EOF'
        #!/bin/bash
        set -e
        
        # 安装必要的构建工具和依赖
        yum -y install wget make gcc pkgconfig
        
        # 下载 Redis 源码
        wget https://github.com/redis/redis/archive/7.2.11.tar.gz
        tar xzf 7.2.11.tar.gz
        
        # 编译 Redis
        cd redis-7.2.11
        make MALLOC=libc
        
        # 复制所有编译好的二进制文件到共享目录
        mkdir -p /output/bin
        cp src/redis-server src/redis-cli src/redis-benchmark src/redis-check-aof src/redis-check-rdb /output/bin/
        EOF
        
        # 创建输出目录
        mkdir -p redis-build
        
        # 使用 Docker 运行 RHEL 7.9 容器进行编译
        docker run --rm -v $(pwd)/build-redis.sh:/build-redis.sh \
                       -v $(pwd)/redis-build:/output \
                       registry.access.redhat.com/ubi7:7.9 \
                       bash -c "chmod +x /build-redis.sh && /build-redis.sh"
        
    - name: Upload Redis binaries as artifact
      uses: actions/upload-artifact@v4
      with:
        name: redis-7.2.11-rhel7.9
        path: redis-build/bin/
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Redis 7.2.11 (RHEL 7.9)
        draft: false
        prerelease: false
        files: |
          redis-build/bin/redis-server
          redis-build/bin/redis-cli
          redis-build/bin/redis-benchmark
          redis-build/bin/redis-check-aof
          redis-build/bin/redis-check-rdb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
